language: python
python:
  - 3.8

dist: focal
services:
  - xvfb

before_install:
  - sudo apt-get update
  - sudo apt install libgl1-mesa-glx libegl1 libglib2.0-0 libxcb-image0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-keysyms1 xserver-xephyr libfontconfig1 libxkbcommon-dev libdbus-1-3 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements/test.txt
  - pip install pytest-xvfb
  - pip install codecov

script:
  - coverage run --source=concertista -m pytest -v -s

after_success:
  - codecov

env:
  global:
    - CI_TEST=YES

branches:
  only:
  - main
